contrib/cabinet/urls.py
from django.conf.urls.defaults import patterns,include, url
from django.views.generic.simple import direct_to_template
import views.section as section
import views.document as document

urlpatterns = patterns('',
    #cabinet urls

    url(r'^add_document/(?P<section>\d+)/$', document.add_document, name='prospere_add_document'),
    url(r'^edit_document/(?P<document_id>\d+)/$', document.edit_document, name='prospere_edit_document'),
    url(r'^change_document_access/$', document.change_document_access, name='prospere_change_document_access'),
    url(r'^delete_document/$', document.delete_document, name = 'prospere_delete_document'),

    # WARNING : Everyone can vote few times
    #url(r'^vote_document/$', 'prospere.contrib.cabinet.views.document.vote_document',name = 'prospere_vote_document'),

    url(r'^add_section/$', section.add_section, name='prospere_add_section'),
    url(r'^edit_section/$', section.edit_section, name='prospere_edit_section'),
    url(r'^change_section_access/$', section.change_section_access, name='prospere_change_section_access'),
    url(r'^delete_section/$', section.delete_section, name = 'prospere_delete_section'),
)

contrib/comment/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
import views

urlpatterns = patterns('',
	url(r'^post_comment/$', views.post_comment, name="prospere_post_comment"),
	url(r'^post_comment_ajax/$', views.post_comment_ajax, name="prospere_post_comment_ajax"),
	url(r'^edit_comment_ajax/$', views.edit_comment_ajax, name="prospere_edit_comment_ajax"),
	url(r'^delete_comment_ajax/$', views.delete_comment_ajax, name="prospere_delete_comment_ajax"),
	url(r'^get_comment_tree/(?P<content_type>\d+)/(?P<object>\d+)/$', views.get_comment_tree, name="prospere_get_comment_tree")
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib.auth import views
from settings import MEDIA_ROOT
#from prospere.copia.views import start_page
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    #Main page and admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('prospere.copia.urls')),
    #include apps urls
    url(r'^comments/', include('prospere.contrib.comment.urls')),
    url(r'^notification/', include('prospere.contrib.notification.urls')),
    url(r'^account/', include('prospere.contrib.account.urls')),
    #url(r'^market/', include('prospere.contrib.market.urls')),
    url(r'^cabinet/', include('prospere.contrib.cabinet.urls')),
    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^error/', direct_to_template, { 'template' : 'error.html'} ),

    #Not prodaction!!!!!
    #url(r'^media/files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': MEDIA_ROOT}),
)

contrib/cabinet/models.py
from django.db import models
from djangosphinx import SphinxSearch
from django.conf import settings
from django.contrib.auth.models import User
from tinymce import models as tinymce_models
import logging
from fields import DocumentFile

from decimal import Decimal
import os
import random

from django.conf import settings
max_depth = getattr(settings,'MAX_PATH_DEPTH')

class Storages(models.Model):

    user = models.ForeignKey(User)
    mem_limit = models.IntegerField(default = 209715200)
    mem_busy = models.IntegerField(default = 0)
    title = models.CharField(max_length = 20, default = "")
    is_store = models.BooleanField(default = False)

    def update_fields(self, **kwargs):
        self.objects.filter(pk=self.pk).update(**kwargs)
    update_fields.alters_data = True

    def __unicode__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'storage'
        verbose_name_plural = 'storages'

class StorageBans(models.Model):

    storage = models.ForeignKey(Storages)
    creation_date = models.DateTimeField(auto_now_add = True)
    is_processed = models.BooleanField()
    amount_of_ban = models.IntegerField()

class PublicSectionManager(models.Manager):

    def get_query_set(self):
        return super(PublicSectionManager,self).get_query_set().filter(is_shared = True)

class Sections(models.Model):

    storage = models.ForeignKey(Storages)
    caption = models.CharField(max_length = 30)
    path = models.CharField(max_length = (max_depth - 1) * 19 + 5, default = '/', db_index = True)
    is_shared = models.BooleanField(default = False)

    public_objects = PublicSectionManager()
    objects = models.Manager()

    def share(self):
        self.is_shared = True
        self.save()

    def hide(self):
        self.is_shared = False
        self.save()        

    def __unicode__(self):
        return self.caption

class PublicDocumentManager(models.Manager):

    def get_query_set(self):
        return super(PublicDocumentManager,self).get_query_set().filter(is_removed = False, is_shared = True)

class NoRemovedDocumentManager(models.Manager):

    def get_query_set(self):
        return super(NoRemovedDocumentManager,self).get_query_set().filter(is_removed = False)

DOCUMENT_DESCRIPTION_MAX_LENGTH = getattr(settings,'DOCUMENT_DESCRIPTION_MAX_LENGTH', 3000)

class Documents(models.Model):

    path = models.CharField(max_length = max_depth * 19 + 5, db_index = True)
    title = models.CharField(max_length = 30)
    description = models.TextField(max_length=DOCUMENT_DESCRIPTION_MAX_LENGTH)
    html_description = tinymce_models.HTMLField(max_length=DOCUMENT_DESCRIPTION_MAX_LENGTH)
    
    file = DocumentFile()
    file_size = models.IntegerField()
	
    user = models.ForeignKey(User)
    storage = models.ForeignKey(Storages)

    is_removed = models.BooleanField(default=False)
    is_moderated   = models.BooleanField(default=False)
    is_shared = models.BooleanField(default = False)
    is_free = models.BooleanField(default=True)

    last_purchase = models.DateTimeField(default=None, blank=True, null=True)

    cost = models.DecimalField(max_digits=6, decimal_places=2, default = Decimal("0.00"))

    creation_date = models.DateTimeField(auto_now_add = True)
    
    count_vote = models.IntegerField(default = 0)
    mark = models.DecimalField(max_digits = 2, decimal_places = 1, default = Decimal("0.0"))

    # WARNING you maust use public user when don't need hidden files
    objects = NoRemovedDocumentManager()
    public_objects = PublicDocumentManager()
    all_objects = models.Manager()

    def hide_file(self, save = True):
        if not self.file.storage.exists(self.file.name): return
        filename = self.file.file.name
        self.file.file.close()
        hash = "_%06x" % random.getrandbits(24)
        name, ext = os.path.splitext(filename)
        available_filename = self.file.storage.get_available_name(name + hash + ext)
        os.rename(filename, available_filename)
        self.file.name = available_filename[available_filename.rindex(DocumentFile.upload_to):]
        if save: self.save()

    def share_file(self, save = True):
        if not self.file.storage.exists(self.file.name): return
        filename = self.file.file.name
        self.file.file.close()
        name, ext = os.path.splitext(filename)
        try:
            name = name[:name.rindex('_')]
        except ValueError:
            logger = logging.getLogger('log')
            logger.error("Warning - share file name don't contain hash")
            return;
        available_filename = self.file.storage.get_available_name(name + ext)
        os.rename(filename, available_filename)
        self.file.name = available_filename[available_filename.rindex(DocumentFile.upload_to):]
        if save: self.save()

    def delete_file(self):
        if self.file.name !='' and self.file.storage.exists(self.file.name):
            self.file.storage.delete(self.file.name)
        
    def delete(self, request = None):
        self.delete_file()
        document_id = self.id
        models.Model.delete(self)

        from signals import document_deleted
        document_deleted.send(sender = None, document_id = document_id )

    def get_file_url(self):
        logger = logging.getLogger('log')
        if self.file.name == '':
            logger.error('Document (id - %s) file name is empty.' % (self.pk) )
            return None
        else:
            if self.file.storage.exists(self.file.name):
                return self.file.url
            else:
                logger.error('Document (id - %s) file does not exist %s' % (self.pk, self.file.name) )
                return None

    search = SphinxSearch(
           index ='document_search', 
           weights = { # individual field weighting
               'title': 100,
               'description': 50,
           }
       )

    def share(self, save = True):
        self.share_file(save = False)
        self.is_shared = True
        if save: self.save()   

    def hide(self, save = True):
        self.hide_file(save = False)
        self.is_shared = False
        if save: self.save()   

    def __unicode__(self):
        return self.title

def create_storage(sender,**kwargs):
    if kwargs['created']:
        Storages.objects.create(user = kwargs['instance'])
models.signals.post_save.connect(create_storage,sender = User)

def increase_storage_mem_busy(sender,**kwargs):
    if kwargs['created']:
        storage = kwargs['instance'].storage
        storage.mem_busy += kwargs['instance'].file_size
        storage.save()
models.signals.post_save.connect(increase_storage_mem_busy, sender = Documents)

def decrease_storage_mem_busy(sender,**kwargs):
    storage = kwargs['instance'].storage
    storage.mem_busy -= kwargs['instance'].file_size
    storage.save()
models.signals.post_delete.connect(decrease_storage_mem_busy, sender = Documents)

contrib/cabinet/forms.py
from django import forms
from models import Documents
from tinymce.widgets import TinyMCE
from django.conf import settings

class AddSectionForm(forms.Form):
    section_caption = forms.CharField(min_length=1,max_length=30)
    def clean_section_caption(self):
        caption = self.cleaned_data.get('section_caption')
        if not len(caption):
            raise forms.ValidationError("wrong caption")
        return caption


DOCUMENT_DESCRIPTION_MAX_LENGTH = getattr(settings,'DOCUMENT_DESCRIPTION_MAX_LENGTH', 3000)

class BaseSaveDocumentForm(forms.Form):
    
    title = forms.CharField(max_length=30,min_length=5)
    #description = forms.CharField(widget = forms.Textarea,max_length = DOCUMENT_DESCRIPTION_MAX_LENGTH)
    html_description = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}),max_length = DOCUMENT_DESCRIPTION_MAX_LENGTH)

    cost = forms.DecimalField(max_digits=5, decimal_places=2, required = False)

    def clean_file(self):
        file = self.cleaned_data.get('file', False)
        if file:
            if file._size > 50 * 1024 * 1024:
                raise forms.ValidationError("Файл слишком большого размера ( > 50mb )")
        return file

    def check_file_size(self, request, storage, old_file_size):
        from django.core.files import File
        file = File(self['file'].value())

        if storage.mem_busy + file.size - old_file_size <= storage.mem_limit:
            return True
        self._errors['file'] = self.error_class(['Недостаточно места для загрузки файла'])
        return False

    def check(self,request, storage, old_file_size = 0):
        flag = self.is_valid()
        if self['file'].value(): flag = self.check_file_size(request, storage, old_file_size) and flag
        return flag
        
class AddDocumentForm(BaseSaveDocumentForm):
    file = forms.FileField()
    is_free = forms.BooleanField(required=False)
    
class EditDocumentForm(BaseSaveDocumentForm):
    file = forms.FileField(required=False)

class VoteForm(forms.Form):
    mark = forms.DecimalField(max_digits=2, decimal_places=1,widget=forms.HiddenInput)
    count_vote = forms.IntegerField(widget=forms.HiddenInput)
    id = forms.IntegerField(widget=forms.HiddenInput)

contrib/cabinet/templates/add_document.html
{% extends "document_canvas.html" %}
{% block head %}{{ form.media }}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.uploadProgress.js"></script> 
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.filestyle.js"></script> 
    <script type="text/javascript">
    $(document).ready(function(){
            $('#id_file').show();
            $("#id_file").filestyle({ 
                 image: "{{ STATIC_URL }}/images/choose_file.png",
                 imageheight : 23,
                 imagewidth : 40,
                 width : 400,
                 style : {"float": "left", "margin-left":'20px', "margin-right":'60px'}
            });
            $('#save_document_button').click(function(){
                $("#title_error").html('');
                $("#description_error").html('');
                $("#file_error").html('');
                var flag = true;
                if ($("#id_title").val().length < 5) {
                    $("#title_error").html("Не менее 5-ти символов.");
                    flag = false;
                }
                if ($("#id_html_description_ifr").contents().text().length < 10) {
                    $("#description_error").html("Не менее 10-ти символов.");
                    flag = false;
                }
                if ($("#id_file").val().length == 0){
                    $("#file_error").html("Выберите файл.");
                    flag = false;
                }
                return flag;
            });

	        $('#upload_form').uploadProgress({
                validation: function(){
                    return true;
                },
		        start: function() {
			        $("#save_document").hide();
                    $("#save_progress").show();
                    $('#progressbar').hide();
                    $('#indicator').progressbar(0);
		        },
		        error: function(upload) {
                    $("#save_progress").hide();
                    $("#save_document").show();
                    $("#file_error").html('Превышен разме файла.');
                    //$('#upload_form')[0].reset();
		        },
		        uploading: function(upload) {
                    $("#upload_percent").html(upload.percents + '%');
                    $('#indicator').progressbar(upload.percents);
                    if ($('#progressbar').is(":hidden")) $('#progressbar').fadeIn(500);
                    if (upload.percents == 100){
                        $("#progress_saving").show();
                    }
		        }
	        });
    });
    </script>
    <style type="text/css">
        .form_error{ color:red; }
        #save_document{}
            #save_document .bright_button{float:right; margin:0px;}
	        #save_document textarea{
		        width: 898px;height: 350px;
                margin:0px; padding:0px;
		        margin-bottom: 15px;
	        }
            #save_document #id_file{ border: none; display:none;}
            #save_document #title_label{ width : auto; margin-right: 10px;}
            #save_document #id_title{ width : 250px; }
    </style>
{% endblock %}
{% block content %}
    {% load copia_filters %}
    {% include "segments/upload_progress.html" %}
	<div id="save_document">
	    <form name="create_document" id="upload_form" action="{{ current_url }}" method="post" enctype = "multipart/form-data">
		    <fieldset>{% csrf_token %}
		        <div class="field_wrapper">
			        <label id="title_label" for="id_title">Введите название:</label>
			        {{ form.title }}
			        <div class="field_error" id="title_error">{{ form.errors.title }}</div>
                    <input type="submit" value="Сохранить" id="save_document_button" class="bright_button" />
			        <br class="clear" />
		        </div>
		
		        <label for="id_description">Описание:</label>
		        <span class="form_error" id="description_error">{{ form.errors.html_description }}</span>
		        {{ form.html_description }}<br />

                {% if storage.is_store %}
                    <script type="text/javascript">
                        function SwitchMode() {
                            if(document.getElementById('id_is_free').checked) {
	                            document.getElementById("id_cost").disabled = true;
	                        } else {
                           	    document.getElementById("id_cost").disabled = false;
	                        }
                        }
                        window.onload = SwitchMode;
                    </script>
                    <div class="box">
                        <input type="checkbox" id="id_is_free" name="is_free" onclick="SwitchMode()" {% if is_free %}checked=""{% endif %} /> 	
                        <label for="id_is_free"> Бесплатно  </label>
                        <div class="r"><label for="id_cost">Стоимость </label>{{ form.cost }}грн.<br class="clear" />
                            <span class="form_error">{{ form.errors.cost }}</span><br class="clear" />
                        </div>
                    </div>
                {% endif %}
                    {% if file_not_requred %}
                        <div class="accentuated_box">
                            Не выбирайте файл, если не хотите заменить существующий.
                        </div>
                    {% endif %}
			        <div id="file_error" class="form_error">{{ form.errors.file }}</div>
			        <label for="id_file" style="float:left; margin-top:2px;">Выберите файл:</label>{{ form.file }}
                    <div style="float:left; margin-top:2px;">свободно: {{ mem_state|convert_byte }}mB</div>
            </fieldset>
	    </form>
	</div>
{% endblock %}

contrib/cabinet/templates/document_canvas.html
{% extends "frame.html" %}

{% block panel_leftside %}
    {% include "segments/panel_searcher.html" %}
{% endblock %}

{% block basis %}
    {% load copia_filters %}    
    <div id="content" style="margin: 0 auto 0 auto; width:900px;">
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

contrib/cabinet/templates/edit_document.html
{% extends "document_canvas.html" %}
{% block head %}{{ form.media }}
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.uploadProgress.js"></script> 
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.filestyle.js"></script> 
    <script type="text/javascript">
    $(document).ready(function(){ 	
            $('#id_file').show();
            $("#id_file").filestyle({ 
                 image: "{{ STATIC_URL }}/images/choose_file.png",
                 imageheight : 23,
                 imagewidth : 40,
                 width : 200,
                 style : {"float": "left", "margin-left":'20px', "margin-right":'60px'}
            });
            $('#save_document_button').click(function(){
                $("#title_error").html('');
                $("#description_error").html('');
                $("#file_error").html('');
                var flag = true;
                if ($("#id_title").val().length < 5) {
                    $("#title_error").html("Не менее 5-ти символов.");
                    flag = false;
                }
                if ($("#id_html_description_ifr").contents().text().length < 10) {
                    $("#description_error").html("Не менее 10-ти символов.");
                    flag = false;
                }
                return flag;
            });

	        $('#upload_form').uploadProgress({
                validation: function(){
                    return true;
                },
		        start: function() {
			        $("#save_document").hide();
                    $("#save_progress").show();
                    $('#progressbar').hide();
                    $('#indicator').progressbar(0);
		        },
		        error: function(upload) {
                    $("#save_progress").hide();
                    $("#save_document").show();
                    $("#file_error").html('Превышен разме файла.');
                    //$('#upload_form')[0].reset();
		        },
		        uploading: function(upload) {
                    $("#upload_percent").html(upload.percents + '%');
                    $('#indicator').progressbar(upload.percents);
                    if ($('#progressbar').is(":hidden")) $('#progressbar').fadeIn(500);
                    if (upload.percents == 100){
                        $("#progress_saving").show();
                    }
		        }
	        });
    });
    </script>
    <style type="text/css">
        .form_error{ color:red; }
        #save_document{color:#222a20;}
            #save_document .bright_button{float:right; margin:0px;}
	        #save_document textarea{
		        width : 898px; height : 350px;
                margin : 0px; padding : 0px;
		        margin-bottom : 15px;
	        }
            #save_document #id_file{ border: none; display:none;}
            #save_document #title_label{ width : auto; margin-right: 10px;}
            #save_document #id_title{ width : 250px; }
    </style>
{% endblock %}
{% block content %}
    {% load copia_filters %}
    {% include "segments/upload_progress.html" %}
	<div id="save_document">
	    <form name="edit_document" id="upload_form" action="{{ current_url }}" method="post" enctype = "multipart/form-data">
		    <fieldset>{% csrf_token %}
		        <div class="field_wrapper">
			        <label id="title_label" for="id_title">Введите название:</label>
			        {{ form.title }}
			        <div class="field_error" id="title_error">{{ form.errors.title }}</div>
    		        <input type="submit" value="Сохранить" id="save_document_button" class="bright_button" /> 
			        <br class="clear" />
		        </div>
		
		        <label for="id_html_description">Описание:</label>
		        <span class="form_error" id="description_error">{{ form.errors.html_description }}</span>
		        {{ form.html_description }}<br />

                {% if is_free %}
                    <div class="small_warning" style="margin-bottom:15px;">
                        <p>Не выбирайте файл, если не хотите заменить существующий.</p>
                    </div>

		            <div id="file_error" class="form_error">{{ form.errors.file }}</div>
		            <label for="id_file" style="float:left;margin-top:2px;">Выберите файл:</label>{{ form.file }}
                    <div style="float:left; margin-top:2px;">свободно: {{ mem_state|convert_byte }}mB</div>
                {% else %}
                    <div class="box"><label for="id_cost">Стоимость </label>{{ form.cost }}грн.<br class="clear" />
                        <span class="form_error">{{ form.errors.cost }}</span><br class="clear" />
                    </div>
                {% endif %}
            </fieldset>
	    </form>
	</div>
{% endblock %}